# Generated by Django 5.1.7 on 2025-03-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=40, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='users/blank_profile_image.png', upload_to='users/profile_images', verbose_name='프로필 이미지'),
        ),
    ]
